apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone
  labels:
    app: udacitycapstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacitycapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacitycapstone
    spec:
      containers:
        - image: nevincansel/udacitycapstone
          imagePullPolicy: Always
          name: udacitycapstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone
  labels:
    app: udacitycapstone
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
